# Generated by Django 4.0.4 on 2022-05-21 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0003_alter_exam_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('в брой', 'В брой'), ('С карта', 'С карта'), ('Банков превод', 'Банков превод')], default='cash', max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='modules.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
