# Generated by Django 4.0.4 on 2022-05-22 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0004_examapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamApplication',
            new_name='UserExams',
        ),
    ]
