# Generated by Django 4.0.4 on 2022-05-22 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0005_rename_examapplication_userexams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExams',
            new_name='ExamRegistration',
        ),
    ]
