# Generated by Django 4.0.4 on 2022-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_rename_userexams_examregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'В брой'), ('card', 'С карта'), ('bank transfer', 'Банков превод')], default='cash', max_length=100),
        ),
    ]
