# Generated by Django 4.0.4 on 2022-05-27 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0008_examregistration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
